/**
 * This file was generated by the Jeddict
 */
package jpafinal.domain;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * @author mrgum
 */
@Entity
public class FootballClubb implements Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long FCID;

    @Basic
    private Double Salary;

    @Basic
    private String PlayingPosition;

    public Long getFCID() {
        return this.FCID;
    }

    public void setFCID(Long FCID) {
        this.FCID = FCID;
    }

    public Double getSalary() {
        return this.Salary;
    }

    public void setSalary(Double Salary) {
        this.Salary = Salary;
    }

    public String getPlayingPosition() {
        return this.PlayingPosition;
    }

    public void setPlayingPosition(String PlayingPosition) {
        this.PlayingPosition = PlayingPosition;
    }

    public FootballClubb() {
    }

    public FootballClubb(Long FCID, Double Salary, String PlayingPosition) {
        this.FCID = FCID;
        this.Salary = Salary;
        this.PlayingPosition = PlayingPosition;
    }

    @Override
    public String toString() {
        return "FootballClubb{" + "FCID=" + FCID + ", Salary=" + Salary + ", PlayingPosition=" + PlayingPosition + '}';
    }

}